const mongoose = require("mongoose");
const express = require("express");
const cors = require("cors");
const fileUpload = require("express-fileupload");

const cron = require("node-cron");
const taskModel = require("./model/taskModel");
const userModel = require("./model/userModel");
const transporter = require("./utils/transporter")



// console.log(os.platform()) //tell which os we have
// console.log(os.arch()) //tell the architecture x32 .x64 , x84 bytes
// console.log(os.hostname()) // tells the name of the device
// console.log(os.release()) // tell the version of the winodw
// console.log(os.cpus()) // tell the details of the cpu
// console.log(os.totalmem()) // tell about the total memory of the device
// console.log(os.freemem()) // tell about the free memory of the device
// console.log(os.userInfo()) // tell about the user details of the device
// console.log(os.homedir()) // tell about the user homedirectiory of the device
// console.log(os.uptime()) // tell about the user  device is ONN for how much time



const app = express()
const port = 6100
const url = "mongodb://localhost:27017/CRUDoperations"

app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: true }));
app.use(fileUpload())


mongoose
  .connect(url)
  .then(() => {
    console.log(">>>> Database Connected");
  })
  .catch((err) => {
    console.log(err);
  });


cron.schedule(
  "0 12 * * *", 
  async () => {
    try {
      console.log("Time :", new Date().toLocaleString());

      const admins = await userModel.find({ role: "admin" });

      console.log("Admins :", admins.length);

      if (admins.length === 0) {
        console.log("No Admin Found");
        return;
      }

      // Find all active pending tasks
      const pendingTasks = await taskModel
        .find({
          status: "pending",
          isactive: true,
        })
        .populate("assignedto", "name email")
        .populate("assignedby", "name email")
        .sort({ duedate: 1 });

      console.log("Pending Tasks :", pendingTasks.length);

      let taskRows = "";

      if (pendingTasks.length > 0) {
        pendingTasks.forEach((task, index) => {
          const overdue =
            new Date(task.duedate) < new Date()
              ? "color:red;font-weight:bold;"
              : "";

          taskRows += `
            <tr>
              <td>${index + 1}</td>
              <td>${task.taskName}</td>
              <td>${task.assignedto?.name || "Not Assigned"}</td>
              <td>${task.assignedby?.name || "Unknown"}</td>
              <td style="${overdue}">
                ${new Date(task.duedate).toLocaleDateString("en-IN")}
              </td>
              <td>${task.status}</td>
            </tr>
          `;
        });
      } else {
        taskRows = `
          <tr>
            <td colspan="6" style="text-align:center;">
              🎉 No Pending Tasks Found
            </td>
          </tr>
        `;
      }

      const html = `
        <h2>Daily Pending Task Report</h2>

        <p><b>Date :</b> ${new Date().toLocaleDateString("en-IN")}</p>

        <p><b>Total Pending Tasks :</b> ${pendingTasks.length}</p>

        <table
          border="1"
          cellpadding="10"
          cellspacing="0"
          style="border-collapse:collapse;width:100%;">

          <thead style="background:#0d6efd;color:white;">
            <tr>
              <th>#</th>
              <th>Task Name</th>
              <th>Assigned To</th>
              <th>Assigned By</th>
              <th>Due Date</th>
              <th>Status</th>
            </tr>
          </thead>

          <tbody>
            ${taskRows}
          </tbody>

        </table>

        <br>

        <p>This mail is automatically generated by Task Manager.</p>
      `;

      for (const admin of admins) {
        console.log("Sending Mail To :", admin.email);

        const result = await transporter.info(
          admin.email,
          "Daily Pending Task Report",
          `
            <h3>Hello ${admin.name},</h3>

            ${html}

            <br>

            <p>Regards,</p>
            <b>Task Manager</b>
          `
        );

        console.log("Mail Sent :", result.messageId);
      }

      console.log("========== CRON COMPLETED ==========");

    } catch (error) {
      console.log("Cron Error");
      console.log(error);
    }
  },
  {
    timezone: "Asia/Kolkata",
  }
);

const userRouter = require("./route/userRoute")
app.use('/taskuser', userRouter)

const taskRouter = require("./route/taskroute");
app.use("/task", taskRouter);

app.listen(port, () => {
  console.log(`>>>> Server is Running on port : ${port}`)
})
